### ISSUE TITLE
[ Discussion - important ]

### ISSUE THREAD

**Issue by sankarbiswas07** [afteracademy/nodejs-backend-architecture-typescript#11]
1. access > token.ts | line : 3  (import { ProtectedRequest } from 'app-request';)
 Q: - **from where you are importing as there is nothing as "app-request" in package.json**

2. how you pass "'x-access-token'" as your postman file has an Authorization header (https://documenter.getpostman.com/view/1552895/SzYUZg52?version=latest#3eb6d8e6-b3a7-455b-b60f-d92bfa13992f).

I was trying to run your code but it gave me an error so I do a modification > added x-access-token in the header and put access token removing "Bearer ". it is working.

Q:- **I didn't find any code block where the Authorization header is cloning the value in x-access-token. I may be wrong.** 

> I would like to hear from you. Thank you for sharing such a great code-bock. really don't know how? But my skeleton(I called it) of the maximum projects is similar with your coding pattern (around 60%). the only difference is I didn't use @hapi/joi and typescript. I am making another skeleton where I want to implement the idea of your logger+ @hapi/joi + few more thing.

**Comment by kubiaq** [comment]
> access > token.ts | line : 3 (import { ProtectedRequest } from 'app-request';)
Q: - from where you are importing as there is nothing as "app-request" in package.json

`app-request` import indicates `app-request.d.ts` file located in `src/types` directory which is specified in `compilerOptions.paths` parameter of `tsconfig.json`.

**Comment by janishar** [comment]
@sankarbiswas07 
1. @sebastianowy already provided the answer.
2. `x-access-token` is deprecated in the new release. You have to use `Authorization  Bearer` scheme now. Check again the latest version of the API doc.

Nice! You will find the joi, typescript, and the other libraries used here will increase your productivity.
