### ISSUE TITLE
[Issue] Can't pass integration test

### ISSUE THREAD

**Issue by kafiln** [afteracademy/nodejs-backend-architecture-typescript#15]
Hello and thank you for your amazing work.

I have read the README and followed all the instructions but I can't seem the make the `integration.test.ts` pass !

It seems like it's not connected to the DB so it can't create a user nor an apiKey, which make all the tests related to it throw error like 

`TypeError: Cannot read property 'key' of null`

Any idea why is this happening ? Am I missing something ? 

Thank you 👍

**Comment by janishar** [comment]
@kafiln Did you use Docker or Manual installation?

**Comment by kafiln** [comment]
@janishar I tried both ! same result

**Comment by janishar** [comment]
@kafiln did this PR solved your issue?

**Comment by kafiln** [comment]
@janishar no, it's not related

**Comment by kafiln** [comment]
@janishar do you pass integration test ? I don't see in the code where the test connect to the db  ? Or is it mocked ?
Thank you for your help 👍

**Comment by janishar** [comment]
Yes it creates the test db. 
To run the test please verify that you are doing the following:
1. Run the docker for the mongo instance
2. Verify that port 27017 is accessible on the localhost and is open
3. You have created .env.test with the database config
```
...
#Databse 
DB_NAME=afteracademy-blog-test-db
DB_HOST=localhost
DB_PORT=27017
DB_USER=afteracademy-blog-test-db-user
DB_USER_PWD=changeit
...
```

**Comment by kafiln** [comment]
Thank you for your help 👍
