### ISSUE TITLE
[bug]: Wrong indexing in the schema

### ISSUE THREAD

**Issue by mythio** [afteracademy/nodejs-backend-architecture-typescript#5]
The KeyStore schema uses multiple indexing which only works if you are using those individual fields to query in the db. So, `findforKey` and `find` in `src/database/repository/KeystoreRepo.ts` will not use the index currently defined.

Inorder to fix this, you need to make two indexes:
1. For `findforKey` which uses compound indexing `{ client: 1, primaryKey: 1 }`
2. For `find` which uses compound indexing `{ client: 1, primaryKey: 1, secondaryKey: 1 }`

This is how the `Keystore` schema should have been indexed.

I am willing to create a pull a request for this change. Please acknowledge. :smiley:

**Comment by janishar** [comment]
Yes you create the pull request
