### ISSUE TITLE
[security]: Flaw in implementation of `refresh-token`

### ISSUE THREAD

**Issue by redd29** [afteracademy/nodejs-backend-architecture-typescript#9]
The idea of sending `refresh-token` is to send a 'SECRET'  key which can then track down the user from the `keystore`. So, the `refresh-token`, should return a `key` of some sort (maybe generated by `crypto` module) instead of JWT. This was brought forward by Auth0, the parent organisation of JWT. I would like to create a PR regarding this. Ping me if you think this idea is good enough :thinking:.

**Comment by janishar** [comment]
@mythio My point of view on this is that the refresh-token JWT has the key generated through crypto. We have to make sure the refresh-token is authentic and this is where the JWT for it is justified.

**Comment by smileatom** [comment]
Couple of points:

1) creating a refresh token with the same exact fields as the access token seems unwise.  A refresh token should only ever be able to be used explicitly for refresh and nothing else.  I know you are checking the ids you issued on them, but be careful.

2)  You never validate the access token that is passed to you in the token.js before refreshing it.  You only check the fields and the subject.  You have not checked to see if its signed. Even though its expired it should not be trusted until the signature is verified.

3)  Why would an app allow an expired JWT to be passed to in an Authorization header and still invoke the route?
IMO an app should never accept an expired Authorization header.  I would suggest either reversing the refresh token and putting it in the header and the access token in the body or passing them both in the body.

**Comment by mythio** [comment]
@smileatom what do you exactly mean by 'reversing the refresh token'?

**Comment by smileatom** [comment]
I mean when the access token is expired, have the client pass the refresh token in the authorization header.

**Comment by janishar** [comment]
@smileatom 
1. Exact same fields are not being used in both `refreshToken` and `accessToken`. `refreshToken` has a unique `refreshTokenKey`. Also, the `refreshToken` is explicitly has one use case i.e. to refresh an expired `accessToken` in the codebase. Check `login.ts` file

2. The `accessToken` is validated for signature. Check `JWT.decode` method. 

3. It does not make any functional difference if you send in `accessToken` in header or body in refresh token API.

**Comment by smileatom** [comment]
The point is the token in a real app should not have any permissions except to do a refresh.  If you werent checking in the database for the id, this token could be used as an access token.

I did look and you did check the sig I was wrong there.

It actually does matter how you pass the token.  In a real system an expired Authorization header should never be processed.
These checks occur up front before any routes are invoked.

**Comment by janishar** [comment]
1. It's by design that the token validity is checked by the id in the database, so I do not agree with the argument you are making here. The token can never be used interchangeably in the codebase. To have more robust system we can implement oauth2. 

2. Yes I agree with you here, it will be better to pass both token in the body of the request. You can make a pull request for it.
